#!/usr/bin/env node
const shell = require('shelljs');
const path = require("path");
const { infoLog } = require('platypus-tools/dist/index');

const rootPath = path.join( __dirname, "/../");

infoLog("================= STOP =================")
shell.exec(`${rootPath}/cli/stop`);
infoLog("================= START =================")
shell.exec(`${rootPath}/cli/start`);
