#!/usr/bin/env node
const path = require('path');
const { Command } = require('commander');
const { startPlatypusProject, getExpandedEnvVars, checkForEnvVarsInObject } = require('platypus-tools/dist/index');

const program = new Command();

program.option(
    `-p, --pull`,
    `docker-compose pull. Pulls an image associated with a service defined in a docker-compose. yml file that defines the service`,
);

program.parse(process.argv);
const options = program.opts();

const rootPath = path.join(__dirname, '/../');
const envFilePath = path.normalize(rootPath + './.env');

const envVars = getExpandedEnvVars(envFilePath);

checkForEnvVarsInObject(["DOCKER_NETWORK", "ENVIRONMENT_TYPE"], envVars);

const dockerNetworkName = envVars.DOCKER_NETWORK;
const environmentType = envVars.ENVIRONMENT_TYPE ?? 'local';

const dockerComposePath = path.normalize(rootPath + `./docker-compose.${environmentType}.yml`);

startPlatypusProject({
    dockerNetworkName,
    dockerComposePath,
    pull: options.pull,
});
