#!/usr/bin/env node
const path = require('path');
const { stopPlatypusProject, checkForEnvVarsInObject, getExpandedEnvVars } = require("platypus-tools/dist/index");

const rootPath = path.join(__dirname, '/../');
const envFilePath = path.normalize(rootPath + './.env');

const envVars = getExpandedEnvVars(envFilePath);

checkForEnvVarsInObject(["DOCKER_NETWORK", "ENVIRONMENT_TYPE"], envVars);

const dockerNetworkName = envVars.DOCKER_NETWORK;
const environmentType = envVars.ENVIRONMENT_TYPE ?? 'local';

const dockerComposePath = path.normalize(rootPath + `./docker-compose.${environmentType}.yml`);

stopPlatypusProject({dockerNetworkName, dockerComposePath});
